Repository vibe-d/vibe.d, pull requests merged in 2019-12, with the labels that each got.

#2355 [Trivial] add comment for SSL_OP_SINGLE_DH_USE and SSL_OP_SINGLE_ECDH…
  tls/vibe/stream/openssl.d
Labels: trivial

#2365 [WIP] Mark vibe.crypto.passwordhash as deprecated
  crypto/vibe/crypto/passwordhash.d
  source/vibe/vibe.d
Labels: WIP

#2392 Enable the manual "openssl-1.1" configuration on Windows.
  tls/dub.sdl
Labels: auto-merge

#2395 Windows OpenSSL upgrade
  lib/win-amd64/libcrypto-1_1-x64.dll
  lib/win-amd64/libssl-1_1-x64.dll
  lib/win-i386/libcrypto-1_1.dll
  lib/win-i386/libssl-1_1.dll
  tls/dub.sdl
Labels: auto-merge

#2201 Do mongo handshake and store ServerDescription on connection
  .travis.yml
  mongodb/vibe/db/mongo/connection.d
  mongodb/vibe/db/mongo/sasl.d
  mongodb/vibe/db/mongo/settings.d
  tests/mongodb/.gitignore
  tests/mongodb/_connection/dub.json
  tests/mongodb/_connection/run.sh
  tests/mongodb/_connection/source/app.d
  tests/mongodb/insert-remove-aggregate/dub.json
  tests/mongodb/insert-remove-aggregate/source/app.d
  travis-ci.sh
Labels: auto-merge
